# /*******************************************************************************
#  * Copyright 2020 古桥教育
#  * @author: 灰哥哥 1778006949@qq.com
#  * added: Feb 10, 2020
#  *******************************************************************************/
apiVersion: v1
kind: Service
metadata:
  name: kafkabroker
  namespace: default
spec:
  selector:
    app: kafkabroker
    release: guqiao
  ports:
  - name: kafka
    protocol: TCP
    port: 9092
    targetPort: 9092
     
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kafkabroker-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: kafkabroker
      release: guqiao
  template:
    metadata:
      labels:
        app: kafkabroker
        release: guqiao
    spec:
#      hostNetwork: true
      hostname: kafkabroker
      containers:
      - name: kafkabroker
        image: wurstmeister/kafka:2.11-0.11.0.3
        ports:
          - name: http
            protocol: TCP
            containerPort: 9092
        env:
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafkabroker:9092"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://:9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper:2181"
          - name: KAFKA_CREATE_TOPICS
            value: "edgexKafkaTopic:2:1"
        volumeMounts:
          - mountPath: "/var/run/docker.sock"
            name: kafkasock
      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: kafkasock

