# /*******************************************************************************
#  * Copyright 2020 古桥教育
#  * @author: 灰哥哥 1778006949@qq.com
#  * added: Feb 10, 2020
#  *******************************************************************************/
apiVersion: v1
kind: Service
metadata:
  name: edgex-core-consul
  namespace: default
spec:
  selector:
    app: edgex-core-consul
    release: guqiao
  ports:
  - name: aa
    protocol: TCP
    port: 8500
    targetPort: 8500
  - name: bb    
    protocol: TCP
    port: 8400
    targetPort: 8400
  - name: cc    
    protocol: TCP
    port: 8600
    targetPort: 8600      
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgex-core-consul-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: edgex-core-consul
      release: guqiao
  template:
    metadata:
      labels:
        app: edgex-core-consul
        release: guqiao
    spec:
      hostname: edgex-core-consul
      containers:
      - name: edgex-core-consul
        image: consul:1.3.1
        ports:
        - name: aa            
          protocol: TCP
          containerPort: 8500
        - name: bb              
          protocol: TCP
          containerPort: 8400
        - name: cc              
          protocol: TCP
          containerPort: 8600
        args:
          - "agent"
          - "-server"
          - "-bootstrap-expect=1"
          - "-ui"
          - "-client=0.0.0.0"
        volumeMounts:
        - mountPath: "/consul/config"
          name: nfs-pvconsulconfig-go
        - mountPath: "/consul/data"
          name: nfs-pvconsuldata-go

      volumes:
        - name: nfs-pvconsulconfig-go
          persistentVolumeClaim:
            claimName: nfs-pvcconsulconfig-go
        - name: nfs-pvconsuldata-go
          persistentVolumeClaim:
            claimName: nfs-pvcconsuldata-go
                       
