# /*******************************************************************************
#  * Copyright 2020 古桥教育
#  * @author: 灰哥哥 1778006949@qq.com
#  * added: Feb 10, 2020
#  *******************************************************************************/
apiVersion: v1
kind: Service
metadata:
  name: edgex-core-command
  namespace: default
spec:
  selector:
    app: edgex-core-command
    release: guqiao
  ports:
  - name: aa
    protocol: TCP
    port: 48082
    targetPort: 48082
     
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgex-core-command-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: edgex-core-command
      release: guqiao
  template:
    metadata:
      labels:
        app: edgex-core-command
        release: guqiao
    spec:
      hostname: edgex-core-command
      containers:
      - name: edgex-core-command
        image: guqiaochina/docker-core-command-go:1.1.0
        ports:
        - name: http
          protocol: TCP
          containerPort: 48082
        env:
          - name: EDGEX_SECURITY_SECRET_STORE
            value: "false"
          - name: edgex_registry
            value: "consul://edgex-core-consul:8500"
          - name: Clients_CoreData_Host
            value: "edgex-core-data"
          - name: Clients_Logging_Host
            value: "edgex-support-logging"
          - name: Logging_EnableRemote
            value: "true"
        volumeMounts:
        - mountPath: "/edgex/logs"
          name: nfs-pvlogs-go

      volumes:
        - name: nfs-pvlogs-go
          persistentVolumeClaim:
            claimName: nfs-pvclogs-go
                       
