# /*******************************************************************************
#  * Copyright 2020 古桥教育
#  * @author: 灰哥哥 1778006949@qq.com
#  * added: Feb 10, 2020
#  *******************************************************************************/
apiVersion: v1
kind: Service
metadata:
  name: edgex-support-notifications
  namespace: default
spec:
  selector:
    app: edgex-support-notifications
    release: guqiao
  ports:
  - name: http
    protocol: TCP
    port: 48060
    targetPort: 48060
     
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgex-support-notifications-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: edgex-support-notifications
      release: guqiao
  template:
    metadata:
      labels:
        app: edgex-support-notifications
        release: guqiao
    spec:
      hostAliases:
      - ip: "59.111.176.14"
        hostnames:
          - "smtp.ym.163.com"
      hostname: edgex-support-notifications
      containers:
      - name: edgex-support-notifications
        image: guqiaochina/docker-support-notifications-go:1.1.0
        ports:
        - name: http            
          protocol: TCP
          containerPort: 48060
        env:
          - name: EDGEX_SECURITY_SECRET_STORE
            value: "false"
          - name: edgex_registry
            value: "consul://edgex-core-consul:8500"
          - name: Clients_CoreData_Host
            value: "edgex-core-data"
          - name: Clients_Logging_Host
            value: "edgex-support-logging"
          - name: Logging_EnableRemote
            value: "true"
        volumeMounts:
        - mountPath: "/edgex/logs"
          name: nfs-pvlogs-go

      volumes:
        - name: nfs-pvlogs-go
          persistentVolumeClaim:
            claimName: nfs-pvclogs-go
                       
