# /*******************************************************************************
#  * Copyright 2020 古桥教育
#  * @author: 灰哥哥 1778006949@qq.com
#  * added: Feb 10, 2020
#  *******************************************************************************/
apiVersion: v1
kind: Service
metadata:
  name: edgex-ui-go
  namespace: default
spec:
  selector:
    app: edgex-ui-go
    release: guqiao
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000
     
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgex-ui-go-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: edgex-ui-go
      release: guqiao
  template:
    metadata:
      labels:
        app: edgex-ui-go
        release: guqiao
    spec:
      hostname: edgex-ui-go
      containers:
      - name: edgex-ui-go
        image: guqiaochina/docker-edgex-ui-go:1.1.1-k8s
        ports:
        - name: http            
          protocol: TCP
          containerPort: 4000
        volumeMounts:
        - mountPath: "/edgex/logs"
          name: nfs-pvlogs-go

      volumes:
        - name: nfs-pvlogs-go
          persistentVolumeClaim:
            claimName: nfs-pvclogs-go
                       
