# /*******************************************************************************
#  * Copyright 2020 古桥教育
#  * @author: 灰哥哥 1778006949@qq.com
#  * added: Feb 10, 2020
#  *******************************************************************************/
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edgex-export-client
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: edgex-export-client
    http:
      paths:
      - path: 
        backend:
          serviceName: edgex-export-client
          servicePort: 48071
