# /*******************************************************************************
#  * Copyright 2020 古桥教育
#  * @author: 灰哥哥 1778006949@qq.com
#  * added: Feb 10, 2020
#  *******************************************************************************/
apiVersion: v1
kind: Service
metadata:
  name: edgex-support-logging
  namespace: default
spec:
  selector:
    app: edgex-support-logging
    release: guqiao
  ports:
    - name: bb
      protocol: TCP
      port: 48061
      targetPort: 48061

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgex-support-logging-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgex-support-logging
      release: guqiao
  template:
    metadata:
      labels:
        app: edgex-support-logging
        release: guqiao
    spec:
      hostname: edgex-support-logging
      containers:
        - name: edgex-support-logging
          image: guqiaochina/docker-support-logging-go:1.1.0
          ports:
            - name: bb
              protocol: TCP
              containerPort: 48061
          env:
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "false"
            - name: edgex_registry
              value: "consul://edgex-core-consul:8500"
            - name: Clients_CoreData_Host
              value: "edgex-core-data"
            - name: Clients_Logging_Host
              value: "edgex-support-logging"
            - name: Logging_EnableRemote
              value: "true"
          volumeMounts:
            - mountPath: "/data/db"
              name: nfs-pvdb-go
            - mountPath: "/edgex/logs"
              name: nfs-pvlogs-go
      volumes:
        - name: nfs-pvdb-go
          persistentVolumeClaim:
            claimName: nfs-pvcdb-go
        - name: nfs-pvlogs-go
          persistentVolumeClaim:
            claimName: nfs-pvclogs-go
                       
